import { redirect } from "next/navigation";
import { getCurrentUser } from "@/lib/auth";
import type { RoleKey } from "@/lib/constants";
import { COMPANY_NAME, roleLabel } from "@/lib/constants";
import { reportsForRole, parseRange, type ReportDef, type ReportRow, type ReportRange } from "@/lib/reports";
import { PrintButton } from "@/components/PrintButton";

// Print / PDF view of all reports the viewer can see (Section 6.7 — "Export all
// reports to Excel / PDF"). Standalone (no app chrome) so it prints clean; the
// user picks "Save as PDF" in the browser print dialog.
export default async function ReportsPrintPage({
  searchParams,
}: {
  searchParams: { from?: string; to?: string };
}) {
  const user = await getCurrentUser();
  if (!user) redirect("/login");
  const role = user.role as RoleKey;

  const params = new URLSearchParams();
  if (searchParams.from) params.set("from", searchParams.from);
  if (searchParams.to) params.set("to", searchParams.to);
  const range = parseRange(params);

  const defs = reportsForRole(role);
  const results = await Promise.all(defs.map(async (d) => ({ def: d, rows: await safeCompute(d, user, range) })));

  const rangeLabel =
    searchParams.from || searchParams.to
      ? `${searchParams.from ?? "…"} to ${searchParams.to ?? "…"}`
      : "All time";

  return (
    <div className="mx-auto max-w-4xl p-8">
      <div className="mb-6 flex items-start justify-between">
        <div className="flex items-center gap-2">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-brand-600 text-sm font-bold text-white">SF</div>
          <div>
            <div className="text-lg font-semibold text-slate-900">{COMPANY_NAME}</div>
            <div className="text-xs text-slate-500">Reports — {roleLabel(user.role)}</div>
          </div>
        </div>
        <div className="text-right">
          <div className="text-sm font-semibold text-slate-900">REPORTS</div>
          <div className="text-xs text-slate-500">Range: {rangeLabel}</div>
          <div className="text-xs text-slate-500">Generated by {user.name}</div>
        </div>
      </div>

      <div className="mb-4 flex justify-end print:hidden">
        <PrintButton />
      </div>

      <div className="space-y-6">
        {results.map(({ def, rows }) => (
          <section key={def.key} className="break-inside-avoid">
            <h3 className="mb-1 text-sm font-semibold text-slate-800">{def.title}</h3>
            <div className="mb-1 text-[11px] uppercase tracking-wide text-slate-400">{def.section}</div>
            {rows.length === 0 ? (
              <p className="text-sm text-slate-400">No data for this range.</p>
            ) : (
              <table className="w-full border-collapse text-sm">
                <thead>
                  <tr className="border-b border-slate-300 text-left text-xs uppercase tracking-wide text-slate-500">
                    {def.columns.map((c, i) => (
                      <th key={c} className={"py-1.5 " + (i === 0 ? "" : "text-right")}>{c}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {rows.map((row, ri) => (
                    <tr key={ri} className="border-b border-slate-100">
                      {row.map((cell, ci) => (
                        <td key={ci} className={"py-1 " + (ci === 0 ? "text-slate-700" : "text-right tabular-nums text-slate-600")}>
                          {cell}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </section>
        ))}
      </div>

      <p className="mt-8 text-xs text-slate-400">This is a computer-generated report from {COMPANY_NAME} CRM.</p>
    </div>
  );
}

async function safeCompute(def: ReportDef, user: Parameters<ReportDef["compute"]>[0], range: ReportRange): Promise<ReportRow[]> {
  try {
    return await def.compute(user, range);
  } catch {
    return [];
  }
}
